### ISSUE TITLE
how do I embed algorithm-visualizer into my frontend?

### ISSUE THREAD

**Issue by tiny1990** [algorithm-visualizer/algorithm-visualizer#288] opened 2020-04-28 08:52 UTC
I want to embed algorithm-visualizer into my web site , but i don't know how  to do it.

**Comment by LzyRapx** [comment] 2020-05-04 18:31
I have the same question too. would someone check this issue？

**Comment by 64json** [comment] 2020-05-08 05:30
Duplicate of #278

**Closed by 64json** 2020-05-08 05:30 UTC
